language: node_js
node_js:
- '12'
before_script:
- npm install -g @angular/cli
- npm run lint:ci
script:
- npm run test:ci
before_deploy:
- npm run build:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: NtNVY5P+RKgToQGoKvdGCMIKL3/j5dy/bt4vHSwSQ1WEHo9o/0jnh2I+nsSiVENGqS48FI5ezRC7phZyIAkuFlKDVWIZGK5NsZYQ4isKdK+CNR9zQ3+V6T3gGuPaLDfM2bL1csTvrFmuBOsZiRtQP6ifSE1jW0LwNN/zmPZfBQ/zklRhBciLX0K2oAs0Zx2Jz9T6gL0Pq+S2JflZhP7qsH4CDa4VwvYjVGYZZoId2kfTR7vQSfadCpSWYZC+8pPKQP3DUT3wzPWkV4U3a5IjGwriJ1qLC6uric5p6UdmiOvvO0iS+M843DDLclpxLrgBHGcYnxhF4eGD0Y0mcUQUhBrqVzjgnpeHiTa7zK/TqFfGB7I+5dhmVxgmMN8d2EZPA/m+Dog6aduqWFDd76x2XJ8NlNdawn2/zAPsLxbI75Ul1GlGKPcKmTDXl5VzSeuFXaM5oNSkDwTX/M+AfMaz8bSUN5r+k1CkYx3H/4mYLwTWmGbnLWyES+0CinWa9TxArJYtKoU9ft7ksoZtySakIae3sIMGLwMjpynyY8PX4Fv/K7332s2TKIaOSAY1EVlwvbil/mVtwIbQvI3Y6d8JyAXX6ZErXLTjINX7d+U5JU0qFVTxaFxo7n1nzxtbSQETPbJmhrV184A0trouFe5R8cGMu07lO6zpqNmaYG7NTbM=
  keep_history: true
  local_dir: dist/Andela-SDG-team006
  on:
    branch: develop
